# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

<<<<<<< HEAD
mainBayesPCA <- function(X, D, I, J, nstart, maxIter, tolerance, svdStart, verbose, updatetau, priorvar, alphatau, betatau, gammatau, deltatau, SVS, priorInclusion, beta1pi, beta2pi, v0, commonpi, JD, Tau, qz, scaleprior, hypertype, globalvar, hpdi) {
    .Call(`_bayespca_mainBayesPCA`, X, D, I, J, nstart, maxIter, tolerance, svdStart, verbose, updatetau, priorvar, alphatau, betatau, gammatau, deltatau, SVS, priorInclusion, beta1pi, beta2pi, v0, commonpi, JD, Tau, qz, scaleprior, hypertype, globalvar, hpdi)
=======
mainBayesPCA <- function(X, D, I, J, nstart, maxIter, tolerance, svdStart, verbose, updatetau, priorvar, alphatau, betatau, JD, Tau, qz, globalvar, hpdi) {
    .Call(`_bayespca_mainBayesPCA`, X, D, I, J, nstart, maxIter, tolerance, svdStart, verbose, updatetau, priorvar, alphatau, betatau, JD, Tau, qz, globalvar, hpdi)
>>>>>>> 50009e97c685ef8e94bbfdb6fc3a466f64df3285
}

